In [50]:
import pandas as pd 

df = pd.read_csv('split1SA1.csv', header=0)
df

title  label kategori
0    jokowi opens th keraton festival in sumenep ea...      0   bisnis
1    fadli zon demands jokowi to free jagorawi of t...      1  politik
2    joko widodo condemned the air strike by israel...      0  politik
3    in marine protection every little bold action ...      1  politik
4             jokowi  strategies for his campaign team      0  politik
5    jokowi ocean preservation requires global ment...     -1  politik
6       sea ocean are our future president jokowi says      0  politik
7         jokowi orders nonstop search for jt airplane      0   bisnis
8    jokowimaruf amin campaign team to assure victo...      0  politik
9    jokowi announces no more toll fee in suramadu ...     -1  politik
10   jokowi condemns gaza missile attack that damag...      0  politik
11   jokowimaruf amin campaign team to assure victo...      0  politik
12   malcolm turnbull jets in for crucial talks wit...      0   bisnis
13      jokowi opens fifth keraton festival in sumenep      0   bisnis
14      indonesian president joko widodo lashes israel      0  politik
15   jokowi campaign team urged not to be too optim...      0  politik
16   president jokowi supports changes in medical w...      0   bisnis
17   president jokowi does not rule out helping doc...      0   bisnis
18        jokowi purchases parka worth rp in  ideafest      1   bisnis
19   rumored as pki member jokowi says his patience...      0  politik
20   jokowimaruf team to convene national working m...      0  politik
21   jokowi asks why people focus more on governmen...      1  politik
22       years of jokowi  jk wiranto relatively stable      0  politik
23   jokowi team sandiaga claim on bung hatta is ma...      0  politik
24   jokowi campaign team defends president sontolo...      0  politik
25   jokowi tells businesses to seek profit from tr...      0   bisnis
26   jokowi esemka car production not government re...      0  politik
27   putin to meet jokowi during russiaasean summit...      0   bisnis
28             putin plans to meet jokowi in singapore      0   bisnis
29   jokowi urges businessmen to tap opportunities ...      0   bisnis
..                                                 ...    ...      ...
814  president jokowi to attend aseanindia summit i...      1   bisnis
815  jokowi calls on banks to expand credits to sma...      1   bisnis
816  jokowi moves closer to golkar in latest cabine...      1  politik
817  rijapan th anniversary should give impetus to ...      0  politik
818  jokowi moves closer to golkar in latest cabine...      1  politik
819  twitter users vent frustrations after jokowi l...     -1   bisnis
820  jokowi revokes cantrang ban susi urges fisherm...      1   bisnis
821  indonesia jokowi reshuffles cabinet as electio...      0  politik
822  president jokowi to reshuffle the cabinet this...      0  politik
823  cantrang fishermen stage rally during jokowi c...      0  politik
824  protesting fishermen leaders meet president jj...      0   bisnis
825  preserve brotherhood despite of different choi...     -1  politik
826   a year of jokowi refugee decree what has changed      0   bisnis
827  indonesia is lucky to have pdip says president...      1  politik
828  jokowi urges ministry to increase fishery prod...      0   bisnis
829  jokowi sides with susi on ship sinking controv...     -1  politik
830   indonesia is lucky to have pdip president jokowi      1  politik
831  indonesian smart cards must be used properly j...      1   bisnis
832  jokowi inaugurates saina water reservoir in ro...      0   bisnis
833    jokowi the first president to reach rote island      1  politik
834   khofifah to deliver resignation letter to jokowi     -1  politik
835  indonesian smart cards should be used properly...      1   bisnis
836  jokowi calls for ethical campaign strategies i...     -1  politik
837  indonesian smart cards must be used properly j...      1   bisnis
838   personnel deployed to secure president jokowi...      1   bisnis
83

In [29]:
dff=df[['title','kategori']] 

In [30]:
dff

title kategori
0    jokowi opens th keraton festival in sumenep ea...   bisnis
1    fadli zon demands jokowi to free jagorawi of t...  politik
2    joko widodo condemned the air strike by israel...  politik
3    in marine protection every little bold action ...  politik
4             jokowi  strategies for his campaign team  politik
5    jokowi ocean preservation requires global ment...  politik
6       sea ocean are our future president jokowi says  politik
7         jokowi orders nonstop search for jt airplane   bisnis
8    jokowimaruf amin campaign team to assure victo...  politik
9    jokowi announces no more toll fee in suramadu ...  politik
10   jokowi condemns gaza missile attack that damag...  politik
11   jokowimaruf amin campaign team to assure victo...  politik
12   malcolm turnbull jets in for crucial talks wit...   bisnis
13      jokowi opens fifth keraton festival in sumenep   bisnis
14      indonesian president joko widodo lashes israel  politik
15   jokowi campaign team urged not to be too optim...  politik
16   president jokowi supports changes in medical w...   bisnis
17   president jokowi does not rule out helping doc...   bisnis
18        jokowi purchases parka worth rp in  ideafest   bisnis
19   rumored as pki member jokowi says his patience...  politik
20   jokowimaruf team to convene national working m...  politik
21   jokowi asks why people focus more on governmen...  politik
22       years of jokowi  jk wiranto relatively stable  politik
23   jokowi team sandiaga claim on bung hatta is ma...  politik
24   jokowi campaign team defends president sontolo...  politik
25   jokowi tells businesses to seek profit from tr...   bisnis
26   jokowi esemka car production not government re...  politik
27   putin to meet jokowi during russiaasean summit...   bisnis
28             putin plans to meet jokowi in singapore   bisnis
29   jokowi urges businessmen to tap opportunities ...   bisnis
..                                                 ...      ...
814  president jokowi to attend aseanindia summit i...  politik
815  jokowi calls on banks to expand credits to sma...   bisnis
816  jokowi moves closer to golkar in latest cabine...  politik
817  rijapan th anniversary should give impetus to ...  politik
818  jokowi moves closer to golkar in latest cabine...  politik
819  twitter users vent frustrations after jokowi l...   bisnis
820  jokowi revokes cantrang ban susi urges fisherm...   bisnis
821  indonesia jokowi reshuffles cabinet as electio...  politik
822  president jokowi to reshuffle the cabinet this...  politik
823  cantrang fishermen stage rally during jokowi c...  politik
824  protesting fishermen leaders meet president jj...   bisnis
825  preserve brotherhood despite of different choi...  politik
826   a year of jokowi refugee decree what has changed   bisnis
827  indonesia is lucky to have pdip says president...  politik
828  jokowi urges ministry to increase fishery prod...  politik
829  jokowi sides with susi on ship sinking controv...  politik
830   indonesia is lucky to have pdip president jokowi  politik
831  indonesian smart cards must be used properly j...  politik
832  jokowi inaugurates saina water reservoir in ro...   bisnis
833    jokowi the first president to reach rote island  politik
834   khofifah to deliver resignation letter to jokowi  politik
835  indonesian smart cards should be used properly...  politik
836  jokowi calls for ethical campaign strategies i...  politik
837  indonesian smart cards must be used properly j...  politik
838   personnel deployed to secure president jokowi...   bisnis
839             sby heaps praises on jokowi government  politik
840    jokowi talks to  rulers about cultural heritage   bisnis
841  jokowi installs djoko setiadi as cybersecurity...  politik
842  jokowi asks ministers to focus on work in poli...  politik
843  jokowi asks ministers to focus on their work i...  politik

[844 rows x 2 columns]

In [31]:
dff.kategori.value_counts()

politik    493
bisnis     351
Name: kategori, dtype: int64

In [32]:
# convert label to a numerical variable
dff['label_num'] = dff.kategori.map({'politik':0, 'bisnis':1})

In [33]:
dff

title kategori  label_num
0    jokowi opens th keraton festival in sumenep ea...   bisnis          1
1    fadli zon demands jokowi to free jagorawi of t...  politik          0
2    joko widodo condemned the air strike by israel...  politik          0
3    in marine protection every little bold action ...  politik          0
4             jokowi  strategies for his campaign team  politik          0
5    jokowi ocean preservation requires global ment...  politik          0
6       sea ocean are our future president jokowi says  politik          0
7         jokowi orders nonstop search for jt airplane   bisnis          1
8    jokowimaruf amin campaign team to assure victo...  politik          0
9    jokowi announces no more toll fee in suramadu ...  politik          0
10   jokowi condemns gaza missile attack that damag...  politik          0
11   jokowimaruf amin campaign team to assure victo...  politik          0
12   malcolm turnbull jets in for crucial talks wit...   bisnis          1
13      jokowi opens fifth keraton festival in sumenep   bisnis          1
14      indonesian president joko widodo lashes israel  politik          0
15   jokowi campaign team urged not to be too optim...  politik          0
16   president jokowi supports changes in medical w...   bisnis          1
17   president jokowi does not rule out helping doc...   bisnis          1
18        jokowi purchases parka worth rp in  ideafest   bisnis          1
19   rumored as pki member jokowi says his patience...  politik          0
20   jokowimaruf team to convene national working m...  politik          0
21   jokowi asks why people focus more on governmen...  politik          0
22       years of jokowi  jk wiranto relatively stable  politik          0
23   jokowi team sandiaga claim on bung hatta is ma...  politik          0
24   jokowi campaign team defends president sontolo...  politik          0
25   jokowi tells businesses to seek profit from tr...   bisnis          1
26   jokowi esemka car production not government re...  politik          0
27   putin to meet jokowi during russiaasean summit...   bisnis          1
28             putin plans to meet jokowi in singapore   bisnis          1
29   jokowi urges businessmen to tap opportunities ...   bisnis          1
..                                                 ...      ...        ...
814  president jokowi to attend aseanindia summit i...  politik          0
815  jokowi calls on banks to expand credits to sma...   bisnis          1
816  jokowi moves closer to golkar in latest cabine...  politik          0
817  rijapan th anniversary should give impetus to ...  politik          0
818  jokowi moves closer to golkar in latest cabine...  politik          0
819  twitter users vent frustrations after jokowi l...   bisnis          1
820  jokowi revokes cantrang ban susi urges fisherm...   bisnis          1
821  indonesia jokowi reshuffles cabinet as electio...  politik          0
822  president jokowi to reshuffle the cabinet this...  politik          0
823  cantrang fishermen stage rally during jokowi c...  politik          0
824  protesting fishermen leaders meet president jj...   bisnis          1
825  preserve brotherhood despite of different choi...  politik          0
826   a year of jokowi refugee decree what has changed   bisnis          1
827  indonesia is lucky to have pdip says president...  politik          0
828  jokowi urges ministry to increase fishery prod...  politik          0
829  jokowi sides with susi on ship sinking controv...  politik          0
830   indonesia is lucky to have pdip president jokowi  politik          0
831  indonesian smart cards must be used properly j...  politik          0
832  jokowi inaugurates saina water reservoir in ro...   bisnis          1
833    jokowi the first president to reach rote island  politik          0
834   khofifah to deliver resignation letter to jokowi  politik          0
835  indonesian smart cards should be used properly...  politik          0

In [34]:
# split X and y into training and testing sets
from sklearn.cross_validation import train_test_split

In [51]:
X = dff.title
y = dff.label_num
print(X.shape)
print(y.shape)

(844,)
(844,)


In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(759,)
(85,)
(759,)
(85,)


In [53]:
from sklearn.feature_extraction.text import CountVectorizer

# instantiate the vectorizer
vect = CountVectorizer()

In [59]:
X_train

693    jokowi hopes indonesia music gains worldwide r...
25     jokowi tells businesses to seek profit from tr...
380    puan maharani on jokowi running mate discussed...
780              something wrong indonesia export jokowi
268         jokowi picks cleric running mate  asean plus
408    jokowi calls for unity despite choice differen...
133    kpu jokowi allowed to use presidential aircraf...
483     jokowi signs regulation on eid alfitr allowances
168    jokowi vows to certify  thousand lands in grob...
509    jokowi asserts cantrang ban not politically dr...
671    pkb chairman proposes himself as vp candidate ...
470    jokowi modi to discuss economy maritime and in...
531    jokowi declines to comment on his minister lea...
5      jokowi ocean preservation requires global ment...
353    mahfud airlangga tgb on vp candidates list jok...
478    jokowi signs rule to require sale of premium g...
713    jokowi comments on home confinement for abu ba...
185                        joko

In [61]:
X_test

318    jokowi electability remains high amid voter sa...
733    many worship places still on disputed lands jo...
474    jokowi wannabe ticketed for not having mirrors...
745    no plan to partner jokowi with prabowo party o...
217    president jokowi sees off indonesian peacekeep...
457                       jokowi receives indian pm modi
557                               tough fight for jokowi
227    court verdict jokowi guilty in kalimantan fore...
838     personnel deployed to secure president jokowi...
342    who will be jokowi new vice president in indon...
120                             i am not pki says jokowi
312    jokowi to meet coalition parties in bogor pala...
331    bawaslu reports on regional election supervisi...
632    gatot nurmantyo says to beat jokowi in spendin...
134    woman breaking jokowi motorcade violates  traf...
259    asman abnur quits jokowi cabinet as pan joins ...
623    five sectors backbone for fourth industrial re...
797                    indonesi

In [62]:
y_train

693    1
25     1
380    0
780    1
268    0
408    0
133    0
483    1
168    0
509    0
671    0
470    1
531    0
5      0
353    0
478    1
713    0
185    0
124    0
403    0
833    0
385    1
638    0
379    1
464    1
820    1
573    0
662    1
314    1
715    0
      ..
712    0
653    0
741    1
19     0
750    0
225    1
732    0
697    0
686    0
710    0
189    0
837    0
593    1
579    0
436    0
444    0
607    1
317    0
841    0
802    0
727    1
420    0
668    1
118    1
746    0
386    0
793    0
226    1
85     0
320    0
Name: label_num, Length: 759, dtype: int64

In [63]:
# learn training data vocabulary, then use it to create a document-term matrix
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)

# or

# equivalently: combine fit and transform into a single step
# X_train_dtm = vect.fit_transform(X_train)

In [64]:
X_train_dtm

<759x1990 sparse matrix of type '<class 'numpy.int64'>'
	with 6341 stored elements in Compressed Sparse Row format>

In [65]:
# transform testing data (using fitted vocabulary) into a document-term matrix
X_test_dtm = vect.transform(X_test)
# X_test_dtm

# NAIVE BAYES

In [66]:
# import and instantiate a Multinomial Naive Bayes model
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [67]:
# train the model using X_train_dtm (timing it with an IPython "magic command")
%time nb.fit(X_train_dtm, y_train)

Wall time: 7 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [68]:
# make class predictions for X_test_dtm
y_pred_class = nb.predict(X_test_dtm)

In [69]:
y_pred_class

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0],
      dtype=int64)

In [70]:
X_test

318    jokowi electability remains high amid voter sa...
733    many worship places still on disputed lands jo...
474    jokowi wannabe ticketed for not having mirrors...
745    no plan to partner jokowi with prabowo party o...
217    president jokowi sees off indonesian peacekeep...
457                       jokowi receives indian pm modi
557                               tough fight for jokowi
227    court verdict jokowi guilty in kalimantan fore...
838     personnel deployed to secure president jokowi...
342    who will be jokowi new vice president in indon...
120                             i am not pki says jokowi
312    jokowi to meet coalition parties in bogor pala...
331    bawaslu reports on regional election supervisi...
632    gatot nurmantyo says to beat jokowi in spendin...
134    woman breaking jokowi motorcade violates  traf...
259    asman abnur quits jokowi cabinet as pan joins ...
623    five sectors backbone for fourth industrial re...
797                    indonesi

In [71]:
y_test

318    0
733    1
474    0
745    0
217    1
457    1
557    0
227    1
838    1
342    0
120    0
312    0
331    0
632    0
134    1
259    0
623    1
797    1
554    0
431    0
373    0
588    1
786    1
635    0
249    0
473    0
376    0
250    1
58     1
493    1
      ..
304    0
157    1
102    1
639    1
828    0
31     0
696    0
708    0
767    1
211    0
504    1
84     1
580    1
832    1
122    0
597    1
199    1
10     0
523    1
372    0
146    0
614    1
22     0
237    0
539    1
449    0
115    1
224    0
392    1
280    0
Name: label_num, Length: 85, dtype: int64

In [72]:
y_pred_class #[1,1] artinya kalimat 5 masuk ke kategori 1, kalimat 9 masuk ke kategori 1

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0],
      dtype=int64)

In [73]:
# calculate accuracy of class predictions
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.6705882352941176

In [74]:
y_test

318    0
733    1
474    0
745    0
217    1
457    1
557    0
227    1
838    1
342    0
120    0
312    0
331    0
632    0
134    1
259    0
623    1
797    1
554    0
431    0
373    0
588    1
786    1
635    0
249    0
473    0
376    0
250    1
58     1
493    1
      ..
304    0
157    1
102    1
639    1
828    0
31     0
696    0
708    0
767    1
211    0
504    1
84     1
580    1
832    1
122    0
597    1
199    1
10     0
523    1
372    0
146    0
614    1
22     0
237    0
539    1
449    0
115    1
224    0
392    1
280    0
Name: label_num, Length: 85, dtype: int64

In [75]:
y_pred_class #[1,1] artinya kalimat 5 masuk ke kategori 1, kalimat 9 masuk ke kategori 1

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0],
      dtype=int64)

In [76]:
# print the confusion matrix
metrics.confusion_matrix(y_test, y_pred_class)

array([[38, 10],
       [18, 19]], dtype=int64)

In [77]:
new_article = ['jokowi ride motorcycle']
new_article_vect = vect.transform(new_article)
nb.predict(new_article_vect)

# {'politik':0, 'bisnis':1}

array([0], dtype=int64)

# svm

In [78]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler(with_mean = False)  
scaler.fit(X_train_dtm)

X_training_vector = scaler.transform(X_train_dtm)  
X_test_vector = scaler.transform(X_test_dtm)

C:\Users\Fitria Nurul Azizah\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [79]:
from sklearn import svm
from sklearn.metrics import accuracy_score
clf = svm.SVC(kernel='linear')
print("Training Classifier...")
%time clf.fit(X_training_vector, y_train)
print("Predicting...")
prediction = clf.predict(X_test_vector)
print("Prediction:",prediction)
accuracy = accuracy_score(y_test, prediction)
# metrics.accuracy_score(y_test, y_pred_class)
print('Accuracy:', accuracy)

Training Classifier...
Wall time: 279 ms
Predicting...
Prediction: [0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0
 1 0 0 1 0 0 0 1 1 0 0 1 1 0 0 0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 0
 0 1 1 1 0 0 1 0 1 1 1]
Accuracy: 0.6823529411764706


In [80]:
metrics.accuracy_score(y_test, prediction)

0.6823529411764706

In [81]:
# print(y_test)
print(prediction)

[0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0
 1 0 0 1 0 0 0 1 1 0 0 1 1 0 0 0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 0
 0 1 1 1 0 0 1 0 1 1 1]


In [82]:
new_article = ['jokowi ride motorcycle']
new_article_vect = vect.transform(new_article)
clf.predict(new_article_vect)


array([0], dtype=int64)