In [1]:
corpus = ['I saw the saw.',
     'I saw her standing there.',
     'Ofcourse I give her an umbrella.',
     'But she give me the saw.',
     'I come but she run.']

In [2]:
# index_value={i[1]:i[0] for i in vectorizer.vocabulary_.items()}

C:\Users\Fitria Nurul Azizah\Anaconda3\lib\site-packages\ipykernel\parentpoller.py:116: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")


In [3]:
# fully_indexed = []
# for row in X:
#     fully_indexed.append({index_value[column]:value for (column,value) in zip(row.indices,row.data)})

In [4]:
# fully_indexed

In [5]:
# index_value

In [6]:
# vectorizer.get_feature_names()

In [7]:
# import and instantiate CountVectorizer (with the default parameters)
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()

In [ ]:
# CountVectorizer?

In [8]:
# learn the 'vocabulary' of the training data (occurs in-place)
vect.fit(corpus)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [62]:
# examine the fitted vocabulary
vect.get_feature_names()

[u'an',
 u'but',
 u'come',
 u'give',
 u'her',
 u'me',
 u'ofcourse',
 u'run',
 u'saw',
 u'she',
 u'standing',
 u'the',
 u'there',
 u'umbrella']

In [10]:
# transform training data into a 'document-term matrix'
simple_train_dtm = vect.transform(corpus)

In [11]:
# convert sparse matrix to a dense matrix
simple_train_dtm.toarray()

#back of word, kumpulan kata yg dilist

array([[0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0]], dtype=int64)

In [12]:
import pandas as pd
# examine the vocabulary and document-term matrix together
pd.DataFrame(simple_train_dtm.toarray(), columns=vect.get_feature_names())

an  but  come  give  her  me  ofcourse  run  saw  she  standing  the  \
0   0    0     0     0    0   0         0    0    2    0         0    1   
1   0    0     0     0    1   0         0    0    1    0         1    0   
2   1    0     0     1    1   0         1    0    0    0         0    0   
3   0    1     0     1    0   1         0    0    1    1         0    1   
4   0    1     1     0    0   0         0    1    0    1         0    0   

   there  umbrella  
0      0         0  
1      1         0  
2      0         1  
3      0         0  
4      0         0

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

#semakin sering kata itu muncul dalam 1 artikel berarti semakin tidak penting nilai katanya
#semakin sering kata itu muncul dalam banyak artikel berarti semakin penting nilai katanya
#kalau entropi itu kalimat

['an', 'but', 'come', 'give', 'her', 'me', 'ofcourse', 'run', 'saw', 'she', 'standing', 'the', 'there', 'umbrella']


In [14]:
# index_value={i[1]:i[0] for i in vectorizer.vocabulary_.items()}

# fully_indexed = []
# for row in X:
#     fully_indexed.append({index_value[column]:value for (column,value) in zip(row.indices,row.data)})

In [15]:
pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names())

an       but      come      give       her       me  ofcourse  \
0  0.00000  0.000000  0.000000  0.000000  0.000000  0.00000   0.00000   
1  0.00000  0.000000  0.000000  0.000000  0.458270  0.00000   0.00000   
2  0.48214  0.000000  0.000000  0.388988  0.388988  0.00000   0.48214   
3  0.00000  0.400791  0.000000  0.400791  0.000000  0.49677   0.00000   
4  0.00000  0.444002  0.550329  0.000000  0.000000  0.00000   0.00000   

        run       saw       she  standing       the     there  umbrella  
0  0.000000  0.856606  0.000000  0.000000  0.515971  0.000000   0.00000  
1  0.000000  0.380406  0.000000  0.568014  0.000000  0.568014   0.00000  
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   0.48214  
3  0.000000  0.332693  0.400791  0.000000  0.400791  0.000000   0.00000  
4  0.550329  0.000000  0.444002  0.000000  0.000000  0.000000   0.00000

In [16]:
# example text for model testing
simple_test = ["i give the saw"]

In [17]:
# transform testing data into a document-term matrix (using existing vocabulary)
simple_test_dtm = vect.transform(simple_test)
simple_test_dtm.toarray()

array([[0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0]], dtype=int64)

In [19]:
# examine the vocabulary and document-term matrix together
pd.DataFrame(simple_test_dtm.toarray(), columns=vect.get_feature_names())

an  but  come  give  her  me  ofcourse  run  saw  she  standing  the  \
0   0    0     0     1    0   0         0    0    1    0         0    1   

   there  umbrella  
0      0         0

In [20]:
from sklearn.cross_validation import train_test_split

C:\Users\Fitria Nurul Azizah\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [22]:
corpus = []
corpus.append({'text':'I saw the saw.','sentiment':'0'})
corpus.append({'text':'I saw her standing there.', 'sentiment':'1'})
corpus.append({'text':'Ofcourse I give her an umbrella.','sentiment':'1'})
corpus.append({'text':'But she give me the saw.', 'sentiment':'-1'})
corpus.append({'text':'I come but she run.', 'sentiment':'-1'})

In [23]:
news_corpus = pd.DataFrame.from_dict(corpus)

In [24]:
X = news_corpus.text
y = news_corpus.sentiment
print(X.shape)
print(y.shape)

(5,)
(5,)


In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


(4,)
(1,)
(4,)
(1,)


In [26]:
news_corpus

sentiment                              text
0         0                    I saw the saw.
1         1         I saw her standing there.
2         1  Ofcourse I give her an umbrella.
3        -1          But she give me the saw.
4        -1               I come but she run.

In [27]:
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)


In [28]:
X_test_dtm = vect.transform(X_test)

In [29]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [30]:
%time nb.fit(X_train_dtm, y_train)

Wall time: 99.1 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [31]:
y_pred_class = nb.predict(X_test_dtm)

In [32]:
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.0

In [33]:
metrics.confusion_matrix(y_test, y_pred_class)

array([[0, 0],
       [1, 0]], dtype=int64)

In [34]:
X_test

2    Ofcourse I give her an umbrella.
Name: text, dtype: object

In [36]:
test1 = ['saw your saw i']
new_article_vect = vect.transform(test1)
nb.predict(new_article_vect)

array(['0'], dtype='<U2')